### PR TITLE
Getting rid of the warnings

### PR DESCRIPTION
**Pull request by ghost**
Here you go :)
This is about the two function updates mentioned earlier;
GrabComponent -> GrabComponentAtLocationWithRotation
AttachTo -> AttachToComponent
where the difference between this and last prq is the WithRotation bit (and related FRotator argument) on the first replaced function, that went missing before last prq because im an idiot :P

### CODE REVIEW

**Comment by ghost** [comment]
The merge conflict seems to be about the double function replace, not sure how to set up on my end so that i can merge your master into mine and save you the effort of resolving the merge conflict :( it should be straightforward though

**Comment by 1runeberg** [comment]
Hi – Normally you’d update your version first with what’s on master then do your revisions. I’ll do a test and resolve, hopefully by Wed or at the latest Friday as I’m doing some commissioned VR project work at the moment.

Cheers,
Rune.

**Comment by ghost** [comment]
Heya,

Yeah, honestly thats what im used to doing (workin with git for years, just never on github) but im not at all used to working on a fork, ill have a look around if i can find how to merge the master of yours into mine (currentlly thinking maybe i can add your repo as a diff remote?) if i find it i will close this prq and make a new one :)

_edit:_ (dont actually need a new one ofc, see below)

**Comment by ghost** [comment]
Yup that was it, sorry for not just trying this myself earlier, it can be merged now.

The conflict is what i suspected, git got confused about what arguments to keep for the 'GrabComponentAtLocationWithRotation' call on line 136 of RunebergVR_Grabber.cpp

**Comment by 1runeberg** [comment]
Tested and Merged! thanks for your contrib :)

**Comment by ghost** [comment]
Happy to help :)

**Pull request merged**
