### PR TITLE
4.14 support

### PR DESCRIPTION
**Pull request by ghost**
Just a quick commit to save you a couple of minutes, making the RunebergVRPlugin play nice with 4.14 :)

Ive removed a bunch of _bWantsBeginPlay_ references since apparently thats deprecated, changed a reference too _GrabComponent_ into _**GrabComponentAtLocation**_ and an _AttachTo_ into _**AttachToComponent**_ (both obviously taking into account the argument changes)

Also posted in the thread :)

### CODE REVIEW

**Comment by 1runeberg** [comment]
Cool. Thanks!

I’ll test the changes out this weekend and merge.

Cheers,
Rune.

**Comment by ghost** [comment]
Heya,
Cool, my pleasure 👍 
I tested it with your provided example project btw, seemed to be 1on1 with the 4.13 version :) (but yea, prolly good if u check aswell)

I've also posted a question in the related thread on ue forum btw :)

**Comment by 1runeberg** [comment]
HI! Thanks again for your efforts on this, really appreciate it.

However for this particular pull request, I had to reject it due to rotation issues with the Grabber component. The grabbed actor's rotation needed to be constrained so they don't spin whilst grabbed.

Sorry, but I do look forward to your future contribs! Cheers.

**Comment by ghost** [comment]
Heya,
Ah thats one thing i didn't properly test then, my mistake!

I see you've made a commit yourself, that actually works, so thanks for that hehe.

I've been working on an 'advanced grabber' (basically rolling your normal and simple grabber into one, and adding more options like grabbing things with 2 hands, 'grab zones' etc) that i'll prolly make a prq for somewhere over the next week, provided i can get it working right ofc.

Either way, thanks for taking the time to look at my 4.14 implementation, and then doing a better one :P much appreciated, will try make and share some cool additions over the next few weeks as i start building my project around it :)

Again, thanks for & keep up the great work :D

**Comment by ghost** [comment]
If you want, i've found and resolved the issue (was result of me testing things and forgetting to roll that back before prq, im an idiot lol) and can do a new prq, it will get rid of all the warnings about 'outdated' functions

**Comment by 1runeberg** [comment]
Hmmmm didnt notice those warnings. Yeah sure, of course feel free to make another pull request.

Thanks,
Rune.

On 20 Nov 2016 15:50, suicidalbanana notifications@github.com wrote:

If you want, i've found and resolved the issue (was result of me testing things and forgetting to roll that back before prq, im an idiot lol) and can do a new prq, it will get rid of all the warnings about 'outdated' functions

**Comment by 1runeberg** [comment]
Re: advanced grabber

Sounds good. I look forward to it.

Cheers,
Rune.

On 20 Nov 2016 14:12, suicidalbanana notifications@github.com wrote:

Heya,
Ah thats one thing i didn't properly test then, my mistake!

I see you've made a commit yourself, that actually works, so thanks for that hehe.

I've been working on an 'advanced grabber' (basically rolling your normal and simple grabber into one, and adding more options like grabbing things with 2 hands, 'grab zones' etc) that i'll prolly make a prq for somewhere over the next week, provided i can get it working right ofc.

Either way, thanks for taking the time to look at my 4.14 implementation, and then doing a better one :P much appreciated, will try make and share some cool additions over the next few weeks as i start building my project around it :)

Again, thanks for & keep up the great work :D

**Pull request closed without merging**
